### ISSUE TITLE
Set variables from java (as options to the compiler)

### ISSUE THREAD

**Issue by gjdev** [SomMeri/less4j#133]
When integrating LESS into a server side build process it would be extremely handy if one was able to set variables based on runtime information (e.g. a user's style/variant in the current session). I.e. have an extra paramater to compile with a Properties/Map object that contains assignments for variables.

**Comment by emlo** [comment]
Hi, I just wanna ask what state this feature request has.

We'd like to give our users the chance to set for example custom colors in our application which will be stored in a database. Our intention was to use variables in our .less files to reference these values and wanted to set them in some kind of less-compiler-configuration. But it seems that this feature is not implemented yet.

As a workaround we're going to use a custom function which returns the value stored in our database. But I think it would be nicer to have this as a variable reference.

I think it would be possible that we try to contribute a way to provide access to the variable-store in the less4j compiler, but I'm kind of lost :-). I currently don't have a idea where to start and where variables are stored.

**Comment by SomMeri** [comment]
There was no progress on this feature. As a workaround you can do that custom function you suggest or you can simply append 
````
@variable: value;
````

**Comment by SomMeri** [comment]
There was no progress on this feature and pull requests are welcome. 

Another workaround is to print your variables and their values into string and append whole thing at the end of compiled file. E.g. append something like this:
````
@variable1: value1;@variable2: value2; 
````

It will work because last variable definition in less is valid for the whole scope and variables can be used before being declared.

**Comment by SomMeri** [comment]
On less4j internals: [this line](https://github.com/SomMeri/less4j/blob/1e8025fa2b11dd9c96b88547d2a057ef81e6646f/src/main/java/com/github/sommeri/less4j/core/compiler/LessToCssCompiler.java#L95) builds the scope. Scope holds all variables and mixins defined in compiled less file. You can use one of `registerVariable` methods to add variables into it.

Note: the scope object is a tree with the similar structure as abstract syntax tree of compiled less file. You probably want to add variable to global scope, so it does not matter.

Most work will be to create [expression](https://github.com/SomMeri/less4j/blob/0e530bebc9c5ea02a5eeddcf521c27c2ae40b024/src/main/java/com/github/sommeri/less4j/core/ast/Expression.java) corresponding to your new values. You will need to convince [ANTLRParser](https://github.com/SomMeri/less4j/blob/0e530bebc9c5ea02a5eeddcf521c27c2ae40b024/src/main/java/com/github/sommeri/less4j/core/parser/ANTLRParser.java#L29) to parse an expression insted of less file and [ASTBuilder](https://github.com/SomMeri/less4j/blob/0e530bebc9c5ea02a5eeddcf521c27c2ae40b024/src/main/java/com/github/sommeri/less4j/core/parser/ASTBuilder.java#L24) to convert its output into expression object.

**Comment by emlo** [comment]
@SomMeri, thanks for your quick response. The creation of the expression sounds a bit complicated. I will dive into it and check it out. I think it would be the better solution to provide the variable.

**Comment by casph** [comment]
Hi, i'm quite interested about this one, no news?

**Comment by SomMeri** [comment]
@casph There are no news on this feature. I have treated this as a lower priority, because the [workaround](https://github.com/SomMeri/less4j/issues/133#issuecomment-69969803)  is easy to implement. 

If you have use case that can not be reasonably satisfied by [workaround](https://github.com/SomMeri/less4j/issues/133#issuecomment-69969803), I will bump the priority up.

**Comment by casph** [comment]
I'm using a similar workaround but using custom functions to define the variables prepended to my .less: 
    @variable1: function1();
so also for me it's not a priority, but having (like velocity) a context object to pass to the compile method will be easier and cleaner.

**Comment by martin-g** [comment]
Yes. I have also used custom `lookup(key)` function for this before. It worked very nicely. I see no reason for more code for something already available.

**Comment by casph** [comment]
@martin-g you're right about this, but i thinks it's a workaround and not a real solution. Maybe keeping it as low profile development?

**Comment by emlo** [comment]
@casph Hi, I'm sorry, didn't check in for a while. I did not get a working solution in reasonable time using the expression approach, so I too do use custom functions which is sufficient.

**Comment by SomMeri** [comment]
Checklist:
* [ ] parse error in variable name
* [ ] parse error in variable value;
* [ ] compile error in variable value;
* [ ] source mapping - do not generate them for stuff from custom variables
* [ ] detached ruleset as value that references something up
* [ ] happy flow

**Comment by SomMeri** [comment]
Two changes against previous comment:
* Variable names are not parsed, they are accepted as they are.
* External variables generates mapping - their declaration is stored into sourcesContent field of sourcemap.

**Comment by SomMeri** [comment]
Documentation: https://github.com/SomMeri/less4j/wiki/External-variables
