### ISSUE TITLE
Add support for external importer implementation

### ISSUE THREAD

**Issue by a701440** [SomMeri/less4j#205]
Need more flexible support for @import directive with custom importers, when content is not located on the file system and or when @import is used inside of the "compile(String less)" content. Should be similar to "less.Parser.importer" in Less.js

**Comment by M3lkior** [comment]
Hello @SomMeri,

I indirectly use less4j with Wro4j API. So, i can not use this hack to resolve my classpaths resources.

Is it possible to still add this support ?

**Comment by SomMeri** [comment]
It should be already possible with wro4j. Wro4j calls less4j from [Less4jProcessor](https://github.com/alexo/wro4j/blob/395b0f3c6b126a87523e233a5bf766237a52c63c/wro4j-extensions/src/main/java/ro/isdc/wro/extensions/processor/css/Less4jProcessor.java) and that processor uses [locatorFactory](https://github.com/alexo/wro4j/blob/395b0f3c6b126a87523e233a5bf766237a52c63c/wro4j-extensions/src/main/java/ro/isdc/wro/extensions/processor/css/Less4jProcessor.java#L83) property to to locate input files. 


The `locatorFactory` has `@inject` annotation, so it is customizable in wro4j management factory configuration. So, you need to find or create the right `UriLocatorFactory` implementation and configure wro4j to use it.

**Comment by M3lkior** [comment]
Ho, exact :)

Sorry for my ignorance ;)

Thanks @SomMeri
