### ISSUE TITLE
The --include-path option is missing

### ISSUE THREAD

**Issue by gdelhumeau** [SomMeri/less4j#229]
Hello.

I would be very interested to use Less4j for the integration of LESS inside our application (XWiki: http://extensions.xwiki.org/xwiki/bin/view/Extension/LESS+Module).

But I cannot do it if there is no support for the "`--include-path`" option, which allows us to specify a directory where LESS can find the files that we would like to import using "`@import`".

Is there a plan to add this feature in Less4J?

Thanks,

Guillaume from XWiki.

**Comment by brianhks** [comment]
You should just add the CustomFileSource to the code base as MultiFileSource or some such.  I'm using less4j from a script environment and adding custom classes is a pain in the butt.

**Comment by SomMeri** [comment]
@brianhks Good idea, this came up already multiple times. I opened new issue for it #287 . If you have such general classes already written, I would accept pull request.

**Comment by gdelhumeau** [comment]
I've made a pull request for this: https://github.com/SomMeri/less4j/pull/289

**Comment by SomMeri** [comment]
@gdelhumeau Thank you.
