### ISSUE TITLE
Compression can be compressed some more

### ISSUE THREAD

**Issue by SeabassNg** [SomMeri/less4j#279]
I noticed there's still newlines on mixin outputs and on @media rules. If you guys can further compress, that'll be nice.

**Comment by SomMeri** [comment]
Do you have an example of what kind of mixin and `@media` rules combination would you like to optimize?

**Comment by SeabassNg** [comment]
@media (min-width: @screen-sm) and (max-width:1119px) {
    @viewport {
        width: 1120px;
        user-zoom: fixed;
    }
}

becomes....

@media (min-width:768px) and (max-width:1119px) {
  @viewport{width:1120px;user-zoom:fixed;}


.default-margin {
    @media (min-width: @screen-sm) {
        margin:@DefaultMargin;
    }
}

becomes

@media (min-width:768px) {
  .default-margin{margin:20px;}
}

**Comment by SeabassNg** [comment]
Any updates?

**Comment by SomMeri** [comment]
@SeabassNg Fixed, it will go into next release.

**Comment by SeabassNg** [comment]
Thanks for the update. I'm looking forward to using it.

**Comment by SomMeri** [comment]
Just released 1.12.0 version should have this fixed. If there is something remaining, please open a new issues.

**Comment by SeabassNg** [comment]
Thanks
