### ISSUE TITLE
Source Mapping generation shouldn't be done if Link Source Map is set to false and Inline is set to false

### ISSUE THREAD

**Issue by SeabassNg** [SomMeri/less4j#281]
Currently, I'm getting a null pointer exception due to source map generation and fails the entire compilation process despite turning all of source map options off. Please don't run the source map generation code if all options are off.

**Comment by SomMeri** [comment]
I will fix this next week.

**Comment by SeabassNg** [comment]
Any updates?

**Comment by SomMeri** [comment]
@SeabassNg Apologies for saying a week, I should have said a month. I will release right after I fix this which I hope will be in next few days.

**Comment by SeabassNg** [comment]
Thanks for the reply

**Comment by SomMeri** [comment]
I just tried to reproduce the error, but failed. Could you please give me stack trace of that null pointer exception? 

This is how I configured the compiler:
````java
    Configuration configuration = new Configuration();
    configuration.setCssResultLocation(new LessSource.FileSource(cssOutput));
    configuration.getSourceMapConfiguration().setInline(false);
    configuration.getSourceMapConfiguration().setLinkSourceMap(false);
    return configuration;
````

Are you doing something differently?

**Comment by SeabassNg** [comment]
The exception showed up when I was using the Thread Unsafe Compiler and multiple threads were running together. I switched over to the Thread Safe Compiler and it worked.

As for the configuration, I set the link source map to false, but it still went over the source map code. It just didn't add it to the file.

**Comment by SomMeri** [comment]
I will close the issue then.
