### ISSUE TITLE
CSS Guard & appender "when" not working

### ISSUE THREAD

**Issue by EightDJ** [SomMeri/less4j#283]
Somewhere between 1.9.0 and 1.11.0 the "& when" appears to have stopped working:

```
    @my-option: true;
    .test {

        color: pink;

        & when (@my-option = true) {
            button {
                color: white;
            }
            a {
                color: blue;
            }
        }
        
    }
```

**Comment by SomMeri** [comment]
Thank you for the report, I will do bugfixing soon.

**Comment by SomMeri** [comment]
Just released 1.12.0 version should have this fixed. If it is not, please re-open the issue.

**Comment by CptS** [comment]
I think this doesn't work if it's on the top level of the less file.
The example code from http://lesscss.org/features/#css-guards-feature:

```css
& when (@my-option = true) {
  button {
    color: white;
  }
  a {
    color: blue;
  }
}
```

throws the following error:

    Appender symbol is not allowed inside top level rulesets.

**Comment by EightDJ** [comment]
Hi,

That's correct, Less doesn't allow then appended symbol in the root of the document as far as I know.

This isn't always ideal as sometimes it's nice to use for scoping when sharing mixins which run at the root across multiple files.

Thanks for your great work with this compiler!

Thomas

**Comment by CptS** [comment]
It's allowed by Less (see http://jsfiddle.net/qb5t3zbr/) but not by less4j.

We're using a theme which is delivered as css and less version. We want to use the less version but thats sadly impossible with less4j.

**Comment by EightDJ** [comment]
Because of the AST implementation?

I guess it’s a shame but there are also workarounds for it, although not ideal!

Nothing is impossible ;)

**Comment by SomMeri** [comment]
@CptS @EightDJ I opened new issue #286 for top level appender and the fix is already on master branch. 

Unfortunately, I will not be able to do release for next week and half. If you are comfortable compiling and using latest head, then you can use that before I do proper release.

**Comment by EightDJ** [comment]
Great! Thanks very much :)

**Comment by CptS** [comment]
Yeah! Thank you! :)
