### ISSUE TITLE
import inside a selector does not work with CSS files

### ISSUE THREAD

**Issue by josephfinlayson** [SomMeri/less4j#291]
Input LESS
```
.flex-grid {
    @import  "../../../../../bower_components/flexboxgrid/src/css/flexboxgrid.css";
}
```
Output CSS
```
.flex-grid {
  @import "../../../../bower_components/flexboxgrid/src/css/flexboxgrid.css";
}
```

How do I namespace CSS imports? Casting this file to less doesn't work as it uses newer CSS features. e.g.: `@custom-media --md-viewport only screen and (min-width: 62em);`

**Comment by SomMeri** [comment]
@josephfinlayson Which newer CSS features do not work and you need them? If less.js supports them then it is a bug that should be fixed.
