### ISSUE TITLE
Document which version of less.js is supported by less4j

### ISSUE THREAD

**Issue by gdelhumeau** [SomMeri/less4j#294]
Hi.

A nice information to have in the wiki: which version of less.js is supported in less4j.

Example: a new feature is added in the Less language in version 2.42. That would be nice to know if less4j supports this feature so if every feature of 2.42 is supported by less4j.

Thanks,
Guillaume

**Comment by SomMeri** [comment]
I can add it on the released [versions page](https://github.com/SomMeri/less4j/wiki/Released-Versions).

**Comment by gdelhumeau** [comment]
Yes, that would be good to have.

**Comment by mattcoz** [comment]
Just started trying out this great compiler and that's one thing I was looking for. It would be greatly appreciated.
