### ISSUE TITLE
contrast function does not follow less.js spec

### ISSUE THREAD

**Issue by mattcoz** [SomMeri/less4j#297]
>The light and dark parameters can be supplied in either order - the function will calculate their luma values and assign light and dark automatically, which means you can't use this function to select the least contrasting color by reversing the order.

I noticed that I wasn't getting the same colors in my CSS after switching to this compiler. I made a simple test of the contrast function with the light and dark colors in either order and got different results.

**Comment by SomMeri** [comment]
This sounds like a bug, I will fix it.
