### ISSUE TITLE
additional space in css selector since 1.15.0

### ISSUE THREAD

**Issue by gbu-censhare** [SomMeri/less4j#314]
Hi, 
since Version 1.15.0 there is a new additional space in our test file, which i believe shouldn't belong there.

Thanks,

Georg

source  less:
    // Main.less
    
    /* Import all less files */
    
    .clear {
      zoom: 1;
    
      &:before,
      &:after{
        content:"";
        display:table;
      }
      &:after { clear: both; }
    }
    
    .premium-small {
      left: 20px;
    }

output less4j:

    /* Import all less files */
    .clear {
      zoom: 1;
    }
    .clear:before,
    .clear :after {
      content: "";
      display: table;
    }
    .clear:after {
      clear: both;
    }
    .premium-small {
      left: 20px;
    }

output less.js

    /* Import all less files */
    .clear {
      zoom: 1;
    }
    .clear:before,
    .clear:after {
      content: "";
      display: table;
    }
    .clear:after {
      clear: both;
    }
    .premium-small {
      left: 20px;
    }

![less4j-output](https://cloud.githubusercontent.com/assets/12797061/10599150/9b8f21f6-76ff-11e5-9153-65c99507b9fd.png)

**Comment by gbu-censhare** [comment]
seems to persist in 1.15.1:

    [gbu@A-W80090N75RU Desktop]$ java -jar ~/Downloads/less4j-1.15.1.jar main.less.txt 
    /* Import all less files */
    .clear {
      zoom: 1;
    }
    .clear:before,
    .clear :after {
      content: "";
      display: table;
    }
    .clear:after {
      clear: both;
    }
    .premium-small {
      left: 20px;
    }

**Comment by SomMeri** [comment]
The issue was fixed. Since appender adding a space seem to me quite important, I will release into maven soon (at worst tomorrow).

**Comment by gbu-censhare** [comment]
great, thanks!

**Comment by SomMeri** [comment]
@gbu-censhare Less4j-1.15.2 was released. It should be available on maven servers within few minutes.
