### ISSUE TITLE
Please add source jar generation goal to pom.xml

### ISSUE THREAD

**Issue by a701440** [SomMeri/less4j#319]
Something alone the lines:

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
               <artifactId>maven-source-plugin</artifactId>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

**Comment by SomMeri** [comment]
Fixed by #320
