### ISSUE TITLE
Regression in 1.15.x: Detached ruleset is not allowed outside of variable declaration

### ISSUE THREAD

**Issue by gsmet** [SomMeri/less4j#323]
Hi,

We found a regression introduced between 1.14.0 and 1.15.0.

The following snippet was parsed OK in 1.14.0 and throws an exception starting from 1.15.0 (and it's still present in master):
```css
.print() {
  a:not(.btn) {
    text-decoration: none;
  }
  
  .make-grid(sm);
}
```

The exception thrown is the following:
```
org.junit.ComparisonFailure: src/test/resources/compile-basic-features/not/not.less expected:<[]> but was:<[Errors produced by compilation of testCase
ERROR 2:15 Detached ruleset is not allowed outside of variable declaration.
 1: .print() {
 2:   a:not(.btn) {
 3:     text-decoration: none;]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at com.github.sommeri.less4j.AbstractFileBasedTest.assertCorrectErrors(AbstractFileBasedTest.java:94)
	at com.github.sommeri.less4j.AbstractFileBasedTest.compileAndCompare(AbstractFileBasedTest.java:64)
```

If we remove the `:not(.btn)`, it works ok so it seems to be related to the presence of the `:not()`.

-- 
Guillaume

**Comment by SomMeri** [comment]
I fixed the bug. I plan to do new release sometimes next week after #324 . If you need it faster, let me know and I will release within a day.

**Comment by SomMeri** [comment]
Fixed version was just released. If you have problem with it, please let me know.
