### ISSUE TITLE
Create a packaged version that can be used for evil (no json.org license)

### ISSUE THREAD

**Issue by theogimonde** [SomMeri/less4j#326]
Currently the packaged version of less4j seems to include json.org code, which requires a no-evil notice when distributed: http://www.json.org/license.html. This makes it impossible to redistribute the packaged less4j with software that should be possible to use for evil, unless you tediously convince yourself that your usage is not covered by the json.org license. (See https://wiki.debian.org/qa.debian.org/jsonevil for a discussion of the issue.)

It would be more convenient if the packaged less4j did not contain any json.org code.

Also it would be useful if the README.md file contained a section about third-party licenses included in the packaged version.

**Comment by SomMeri** [comment]
Json is used only in tests, not in library itself. Is it a problem in that case too? In any case, I would accept evil friendly pull request (in case you need it faster).

**Comment by theogimonde** [comment]
Thanks for the response! The test code usage of org.json code is unfortunately enough to make it a hard sell with those picky about licenses.

One possible fix would be to replace org.json with an alternative JSON processing library with a more palatable license. I explored three different evil-compatible JSON libraries:

* [gson](/google/gson) (*Pros:* active project, elegant, Apache 2.0. *Cons:* largest library, cannot handle invalid JSON.) - [/theogimonde/less4j/gson-2.5](/theogimonde/less4j/tree/gson-2.5)
* [json-simple](/fangyidong/json-simple) (*Pros:* simple, small library, handles invalid JSON, Apache 2.0. *Cons:* requires ugly casts, no recent commits.) - [/theogimonde/less4j/json-simple-1.1.1](/theogimonde/less4j/tree/json-simple-1.1.1)
* [javax.json](https://jsonp.java.net/) (*Pros:* standardized API, moderate library size. *Cons:* adoption of the standard is yet unclear, CDDL license, cannot handle invalid JSON.) - [/theogimonde/less4j/javax.json-1.04](/theogimonde/less4j/tree/javax.json-1.0.4)

Feel free to pick your poison from either of these branches, or let me know if you would prefer a pull request for one of them. The invalid JSON was an extra comma in two test mapdata files. Those test files have been fixed as needed, but less4j would no longer handle these kinds of JSON errors if gson or javax.json were used. (json-simple was more forgiving in this regard.)

My favorite of the three libraries, after this small coding session, would be gson.

**Comment by SomMeri** [comment]
Wow, thank you. I think that gson sounds the best. I think that if you send pull request from your repo, github should give you attribution for that. If you don't care about it, I will send pull request from your repo before release - commit will be yours, but github history slightly different.

In any case, this will go into the next release - either next week or after #325. If you need it faster let me know and I will release within a day.
