### ISSUE TITLE
Malformed less causes infinite loop

### ISSUE THREAD

**Issue by EXPEphall** [SomMeri/less4j#329]
Attempting to import this malformed less causes less4j to go into an infinite loop (at least I assume it is infinite, it will happily run for at least half an hour):

    a&.b {
      &:c {
      }
    }

less.js compiles it quickly and produces no output. Deleting the first ampersand makes both less4j and less.js compile it quickly to no output.

Discovered while switching a large codebase from lesscss-java to less4j

**Comment by SomMeri** [comment]
@EXPEphall  It is fixed. If you need release fast, please let me know and I will do it. Otherwise I will release in two weeks or so after https://github.com/SomMeri/less4j/pull/330#issuecomment-182754541.

**Comment by EXPEphall** [comment]
Thanks for fixing this. I'm happy to wait until #330 before a release.
