### ISSUE TITLE
ColorExpression.toHex incorrectly prefixes r,g,b values with "0" if they are between 15.5 and 16.0.

### ISSUE THREAD

**Issue by grantyb** [SomMeri/less4j#335]
`color: darken(mix(#38C1D9, #000, 33%), 15%, relative);`

produces an illegal 7-digit color value:

`color: #010363d`

This is caused by an error in `com.github.sommeri.less4j.core.ast.ColorExpression` inside `toHex()` which adds a prefix for values < 16 before rounding.

**Comment by grantyb** [comment]
This issue is resolved by PR #336. I'm not sure about the etiquette of closing this issue? Shall I wait for release 1.17.1?

**Comment by SomMeri** [comment]
No, I just forgot to close it when I was closing #336. I am closing it now and will make release today or tomorrow.
